### ISSUE TITLE
Diff: jednolity format (reprezentacja różnic)

### ISSUE THREAD

**Issue by maciejczyzewski** [Danieluss/IOIO#22]
Aby moc wizualizować różnice w GUI należy wymyślić protokół, tak aby _receiver_ wiedział, jak ma je interpretować.

![image](https://user-images.githubusercontent.com/1976088/69916543-7aeb2900-145c-11ea-9692-65bef867eba2.png)

**Comment by KamilPiechowiak** [comment]
Zaproponowany przeze mnie protokół jest następujący:
- wysyłamy jsona zawierającego teksty do porównania w atrybutach "oldText" i "newText". Przykład: '{"oldText": "ABCDELMN\nPPPP\nXXXX\nnextline\nABC\nAAAA\ntest\n", "newText": "ABCFGLMN\nSTH\nXXXX\nABC\ntest\nBBBB\n"}',
- otrzymujemy jsona zawierającego dwie tablice (po jednej dla każdego tekstu). Każdy element tablicy odpowiada pojedynczej linii w danym tekście. Jeśli jest on równy -1, to dana linia nie została dopasowana. W przeciwnym wypadku jest to indeks dopasowanej linii w drugim tekście. Dla powyższego przykładu dostajemy wynik: "{\"oldText\":[-1,-1,2,-1,3,-1,4],\"newText\":[-1,-1,2,4,6,-1]}".
